kind: Service
apiVersion: v1
metadata:
  name: artcifact-svc
  labels:
    app: artcifact
spec:
  type: NodePort
  selector:
    app: artcifact
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: artcifact-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artcifact
  template:
    metadata:
      labels:
        app: artcifact
        version: v1
    spec:
      containers:
      - name: artcifact-server
        image: artcifact-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
